### ISSUE TITLE
Кнопка Get points должна быть всегда активна

### ISSUE THREAD

**Issue by simgislab** [nextgis/ReconstructLine#3]
И если точки не выбраны работать по всем точкам слоя.

Если есть активная выборка - использовать её.

**Comment by yellow-sky** [comment]
А если слой полигональной?

**Comment by simgislab** [comment]
'Please select point layer', тоже самое с линейным

Главное - не заставлять пользователя догадываться, почему кнопка заблокирована.

**Comment by yellow-sky** [comment]
Тогда можно и вторую разблокировать - если в буфере пусто писать - Please select points

**Comment by simgislab** [comment]
ага
