### ISSUE TITLE
Please add to the about the difference with similar functionality

### ISSUE THREAD

**Issue by pcav** [nextgis/ReconstructLine#5]
Present in qgis standard, so people will know when it is useful to install this one.
Thanks.

**Comment by simgislab** [comment]
hi Paolo

> add to the about

Github? Metadata? About menu in plugin?

Where do people usually add this stuff?

**Comment by yellow-sky** [comment]
It's metadata likely... Or not?

**Comment by simgislab** [comment]
I don't think that long description of how this plugin actually works belongs in metadata.

**Comment by pcav** [comment]
A 4 lines description in the about field of metadata would be nice.
Thanks.
