### ISSUE TITLE
Does it work for Qgis 3?

### ISSUE THREAD

**Issue by stavpup** [nextgis/ReconstructLine#8]
Can not find it for Qgis 3+

**Comment by simgislab** [comment]
It doesn't

**Comment by stavpup** [comment]
It is difficult to port to version 3?

**Comment by CEZERT** [comment]
Hi, it will work if you replace the files connector.py and reconstruct_line.py the I proposed. It work for me in QGIS version 3.4.5

**Comment by eduard-kazakov** [comment]
Plugin is now available for QGIS3 in standard repository
